apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: oauth2-server
          image: vladwoode/oauth2-server:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-server-secret
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-server-secret
                  key: client-secret
          volumeMounts:
            - name: keys
              mountPath: /keys
      volumes:
        - name: keys
          secret:
            secretName: oauth2-server-keys
